apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-collage-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-collage-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-collage-app
    spec:
      containers:
      - name: collage
        image: ghcr.io/xlab-classes/collage-image:latest
        resources:
          limits:
            cpu: "0.5" # Limit the pod to use a maximum of 0.5 CPU cores
            memory: "500Mi" # Limit the pod to use a maximum of 512 megabytes of memory
          requests:
            cpu: "0.2" # Request at least 0.2 CPU cores for the pod
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: collage-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-collage-app
  ports:
  - name: my-app
    port: 8012
    nodePort: 30012
    targetPort: 8012
