apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-frontend-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-frontend-app
    spec:
      containers:
      - name: frontend
        image: saad12ah/photoeditor-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: phototeditor-frontend-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-frontend-app
  ports:
  - name: my-app
    port: 3000
    targetPort: 3000

