apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-frontend-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-frontend-app
    spec:
      containers:
      - name: frontend
        image: saad12ah/frontend
        resources:
          limits:
            cpu: "0.5" # Limit the pod to use a maximum of 0.5 CPU cores
            memory: "1400Mi" # Limit the pod to use a maximum of 512 megabytes of memory
          requests:
            cpu: "0.2" # Request at least 0.2 CPU cores for the pod
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: phototeditor-frontend-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-frontend-app
  ports:
  - name: my-app
    port: 3000
    targetPort: 3000

