apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-mosaic-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-mosaic-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-mosaic-app
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: mosaic
        image: ghcr.io/xlab-classes/mosaic-image:latest
        resources:
          limits:
            cpu: "0.5" # Limit the pod to use a maximum of 0.5 CPU cores
            memory: "100Mi" # Limit the pod to use a maximum of 512 megabytes of memory
          requests:
            cpu: "0.2" # Request at least 0.2 CPU cores for the pod
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mosaic-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-mosaic-app
  ports:
  - name: my-app
    port: 8015
    nodePort: 30015
    targetPort: 8015

