apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-noise-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-noise-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-noise-app
    spec:
      containers:
      - name: noise
        image: saad12ah/noise
        resources:
          limits:
            cpu: "0.5" # Limit the pod to use a maximum of 0.5 CPU cores
            memory: "500Mi" # Limit the pod to use a maximum of 512 megabytes of memory
          requests:
            cpu: "0.2" # Request at least 0.2 CPU cores for the pod
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: noise-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-noise-app
  ports:
  - name: my-app
    port: 8013
    nodePort: 30013
    targetPort: 8013

