apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-passport-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-passport-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-passport-app
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: passport
        image: ghcr.io/xlab-classes/passport-image:latest
        resources:
          limits:
            cpu: "0.5" # Limit the pod to use a maximum of 0.5 CPU cores
            memory: "1400Mi" # Limit the pod to use a maximum of 512 megabytes of memory
          requests:
            cpu: "0.2" # Request at least 0.2 CPU cores for the pod
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: passport-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-passport-app
  ports:
  - name: my-app
    port: 8010
    nodePort: 30010
    targetPort: 8010

