apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototeditor-videocompression-depl
spec:
  selector:
    matchLabels:
      app: photoeditor-videocompression-app
  replicas: 1
  template:
    metadata:
      labels:
        app: photoeditor-videocompression-app
    spec:
      containers:
      - name: videocompression
        image: ghcr.io/xlab-classes/video-compression-image:latest
        resources:
          limits:
            cpu: "0.5" # Limit the pod to use a maximum of 0.5 CPU cores
            memory: "1000Mi" # Limit the pod to use a maximum of 512 megabytes of memory
          requests:
            cpu: "0.2" # Request at least 0.2 CPU cores for the pod
            memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: videocompression-servc
spec: 
  type: NodePort
  selector: 
    app: photoeditor-videocompression-app
  ports:
  - name: my-app
    port: 8018
    nodePort: 30018
    targetPort: 8018

