# Generated by Django 2.2 on 2023-03-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionActivity',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=25)),
                ('function_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'function_activity',
            },
        ),
    ]
