name: Push collage Image to GHCR
on:
  push:
    paths:
      - 'backend/collage/**'
    branches:
      - main # Adjust to the branch that trigger the workflow on
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v3
          - name: set lower case owner name
            run: |
              echo "OWNER_GHRC=${OWNER,,}" >>${GITHUB_ENV}
            env:
              OWNER: '${{ github.repository_owner }}'
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
          - name: ‘Build and Tag Docker Image’
            run: |
              cd backend/collage
              docker build . --tag ghcr.io/${OWNER_GHRC}/collage-image:${{ github.sha }}
              docker tag ghcr.io/${OWNER_GHRC}/collage-image:${{ github.sha }} ghcr.io/${OWNER_GHRC}/collage-image:latest
          - name: ‘Push Image to GHCR’
            run: |
              docker push ghcr.io/${OWNER_GHRC}/collage-image:${{ github.sha }}
              docker push ghcr.io/${OWNER_GHRC}/collage-image:latest